robot:
  name: so101
  base_link: base_link
  tip_link: gripper_link

  arm_joint_names:
    - shoulder_pan
    - shoulder_lift
    - elbow_flex
    - wrist_flex
    - wrist_roll

  gripper_joint_name: gripper

  joints:
    shoulder_pan:
      parent: base_link
      child: shoulder_link
      type: revolute
      origin:
        xyz: [0.0388353, -8.97657e-09, 0.0624]
        rpy: [3.14159, 4.18253e-17, -3.14159]
      axis: [0.0, 0.0, 1.0]
      limits:
        lower: -1.91986
        upper: 1.91986

    shoulder_lift:
      parent: shoulder_link
      child: upper_arm_link
      type: revolute
      origin:
        xyz: [-0.0303992, -0.0182778, -0.0542]
        rpy: [-1.5708, -1.5708, 0.0]
      axis: [0.0, 0.0, 1.0]
      limits:
        lower: -1.74533
        upper: 1.74533

    elbow_flex:
      parent: upper_arm_link
      child: lower_arm_link
      type: revolute
      origin:
        xyz: [-0.11257, -0.028, 1.73763e-16]
        rpy: [-3.63608e-16, 8.74301e-16, 1.5708]
      axis: [0.0, 0.0, 1.0]
      limits:
        lower: -1.69
        upper: 1.69

    wrist_flex:
      parent: lower_arm_link
      child: wrist_link
      type: revolute
      origin:
        xyz: [-0.1349, 0.0052, 3.62355e-17]
        rpy: [4.02456e-15, 8.67362e-16, -1.5708]
      axis: [0.0, 0.0, 1.0]
      limits:
        lower: -1.65806
        upper: 1.65806

    wrist_roll:
      parent: wrist_link
      child: gripper_link
      type: revolute
      origin:
        xyz: [5.55112e-17, -0.0611, 0.0181]
        rpy: [1.5708, 0.0486795, 3.14159]
      axis: [0.0, 0.0, 1.0]
      limits:
        lower: -2.74385
        upper: 2.84121

  end_effector:
    parent: gripper_link
    origin:
      xyz: [-0.0079, -0.000218121, -0.0981274]
      rpy: [0.0, 3.14159, 0.0]

  gripper:
    type: revolute
    limits:
      lower: -0.174533
      upper: 1.74533