<?xml version="1.0"?>
<package format="3">
  <name>so101_bringup</name>
  <version>0.1.0</version>

  <description>
    Launch files and system configuration for the SO-101 robot.
  </description>

  <maintainer email="steve@todo.todo">Steve</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>robot_kinematics</exec_depend>
  <exec_depend>so101_control</exec_depend>
  <exec_depend>so101_description</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>